### ISSUE TITLE
Static weight settings are incorrect

### ISSUE THREAD

**Issue by kenmcd** [redstonedesign/parkinsans#2]
The exported static fonts have the following OS/2 weight settings:

Light ------ 300
Regular --- 400
Medium -- 500
SemiBold - 592 - should be 600
Bold ------- 700
ExtraBold - 400 - should be 800

So the SemiBold and the ExtraBold need to be fixed.
In Glyphs I think that is on the Exports tab.
https://glyphsapp.com/learn/creating-a-variable-font#g-step-4-add-predefined-instances

**Comment by redstonedesign** [comment]
Hi @kenmcd, thank you for pointing this out. I'm still not sure why this was happening, as the ExtraBold and SemiBold instances had the correct weight settings (see below), but I've made some changes to the weight axes coordinates so this may have fixed it.


<img width="707" alt="Screenshot 2024-10-23 at 14 27 55" src="https://github.com/user-attachments/assets/1e332a6f-9662-4d8d-ba83-209684aca145">

<img width="701" alt="Screenshot 2024-10-23 at 14 28 55" src="https://github.com/user-attachments/assets/d6ed5116-ef09-4249-8cf4-97bcfa74e49f">

**Comment by kenmcd** [comment]
The fonts from the workflow - the weights look good now.
