### ISSUE TITLE
Axis Mapping appears to be missing

### ISSUE THREAD

**Issue by kenmcd** [redstonedesign/parkinsans#3]
Used `fontmake` to build the variable font and it does not work correctly.

See Google Fonts docs discussion of Axis Mapping here:
https://googlefonts.github.io/gf-guide/variable#the-axis-mapping

And the Glyphs info here:
https://glyphsapp.com/learn/creating-a-variable-font#g-axis-mappings-and-locations

**Comment by redstonedesign** [comment]
Thanks for this @kenmcd, super helpful. I've now added Axis Mapping, although I'm unsure if this setup is correct as it seems redundant.

<img width="977" alt="Screenshot 2024-10-23 at 14 25 53" src="https://github.com/user-attachments/assets/1236b6f3-bd4e-42db-9d2a-44bc4886ac38">
