### ISSUE TITLE
.notdef should be glyph 0 and a standard shape

### ISSUE THREAD

**Issue by kenmcd** [redstonedesign/parkinsans#4]
OpenType Recommendation and GF requires it.
And GF requires it it be a "standard" form such as a box.

https://learn.microsoft.com/en-us/typography/opentype/spec/recom#glyph-0-the-notdef-glyph

Currently the `.notdef` is glyph 369 in the `.glyphs` source file.

Hmmmm... but it looks like the VF font I built with fontmake has it at 0.
And the statics from gfbuilder also have it at 0.
And it has been changed to a rectangle.
So have to keep an eye on this.

Best to fix it in the Glyphs source to be sure.

**Comment by redstonedesign** [comment]
Thanks for the info here @kenmcd, I wasn't aware of the GF requirement. 

We've replaced the design and I believe I've fixed the order with a glyphOrder parameter in the latest commit.

**Comment by kenmcd** [comment]
This is fixed in the source.
