### ISSUE TITLE
Authors/contributors clarification

### ISSUE THREAD

**Issue by emmamarichal** [redstonedesign/parkinsans#6]
Hi @redstonedesign!

I'm currently working on the final export of the font, and it includes the set up of the copyright metadatas.
In the `designer` field, I plan to put: `Red Stone Design LTD, Indian Type Foundry`, same in the AUTHORS.txt.

Do you want to add anyone? Like the name of the designer who actually work on it, or Red Stone Design is enough? It can also be added in the CONTRIBUTORS.txt

____

As it's a fork of Poppins, we will precise it in the about section, like here for example: https://fonts.google.com/specimen/Bricolage+Grotesque/about

It's also appreciate to have images in the readme, spotting the differences and modifications between the two fonts.
If you have time to prepare one or two images, that would be awesome (no rush, it's not mandatory for the onboarding process)

**Comment by redstonedesign** [comment]
Thanks @emmamarichal, 

In the designer field, can we be listed as just Red Stone, so _"Red Stone, Indian Type Foundry"_ ? And as for the CONTRIBUTORS.txt, we'll just stick with Red Stone. I will merge your pull request now and make these updates in AUTHORS AND CONTRIBUTORS.

And thanks for the info, we will prepare some images for the readme!
